version: '3'
services:
  # Servicio PHP
  php:
    image: php:8.1-fpm
    volumes:
      - ./php:/var/www/html
    ports:
      - "9000:9000"

  # Servicio MySQL
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: dbname
      MYSQL_PASSWORD: test
    volumes:
      - ./mysql:/var/lib/mysql

  # Servicio Nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./php:/var/www/html
    depends_on:
      - php
      - mysql

  # Servicio PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql